import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

// components
import { ThemeProvider } from '@/components/theme-provider';
import { AppBar } from '@/components/parts/app-bar';
import { Bread } from '@/components/parts/bread';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen flex-col antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AppBar />
          <main className="flex grow flex-col space-y-2 min-h-screen bg-gradient-to-b from-[#c9e8ff] to-[#89bcff] px-12 py-6">
            <Bread />
            <div>{children}</div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
